[package]
edition = "2021"
name = "soroban-version-vulnerable-1"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "=21.2.0" }

[dev-dependencies]
soroban-sdk = { version = "=21.2.0", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
