[workspace]
members = ["*"]
exclude = [".cargo", "target"]
resolver = "2"

[workspace.dependencies]
dylint_linting = { package = "scout-audit-dylint-linting", version = "3.0.0" }
dylint_testing = "2.1.5"
if_chain = "1.0.2"

scout-audit-clippy-utils = { version = "=0.2.3" }
