[package]
name = "clippy-wrapper-print-error"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "=0.11.27", features = ["blocking"] }
serde_json = "=1.0.120"
capture-stdio = "=0.1.1"
