[package]
edition = "2021"
name = "assert-violation-remediated-1"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[features]
__ink_dylint_Constructor = []
__ink_dylint_Storage = []
default = ["std"]
ink-as-dependency = []
std = ["ink/std", "scale-info/std", "scale/std"]

[dependencies]
getrandom = { workspace = true, features = ["js"] }
ink = { workspace = true }
scale = { workspace = true }
scale-info = { workspace = true }
