[package]
edition = "2021"
name = "reentrancy-1-remediated-2"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[features]
__ink_dylint_Constructor = []
__ink_dylint_Storage = []
default = ["std"]
ink-as-dependency = []
std = ["ink/std"]

[dependencies]
ink = { workspace = true }
