[package]
edition = "2021"
name = "analysis"
version = "0.1.0"

[dependencies]
if_chain = "=1.0.2"
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "6cc8f8dbaa7ee3ee9b41a23bf38fc9154951c108", package = "clippy_utils" }
paste = "1.0"
dylint_linting = "=3.1.2"

[package.metadata.rust-analyzer]
rustc_private = true
