[auditor]
assert-violation.enabled = true
avoid-core-mem-forget.enabled = false
avoid-format-string.enabled = false
delegate-call.enabled = true
divide-before-multiply.enabled = true
dos-unbounded-operation.enabled = true
dos-unexpected-revert-with-vector.enabled = true
ink-version.enabled = true
insufficiently-random-values.enabled = true
integer-overflow-or-underflow.enabled = true
iterators-over-indexing.enabled = true
lazy-delegate.enabled = true
panic-error.enabled = false
reentrancy-1.enabled = true
reentrancy-2.enabled = true
set-code-hash.enabled = true
set-contract-storage.enabled = true
unprotected-mapping-operation.enabled = true
unprotected-self-destruct.enabled = true
unrestricted-transfer-from.enabled = true
unsafe-expect.enabled = true
unsafe-unwrap.enabled = true
unused-return-enum.enabled = false
zero-or-test-address.enabled = true

[dev]
assert-violation.enabled = true
avoid-core-mem-forget.enabled = true
avoid-format-string.enabled = true
delegate-call.enabled = true
divide-before-multiply.enabled = true
dos-unbounded-operation.enabled = true
dos-unexpected-revert-with-vector.enabled = true
ink-version.enabled = true
insufficiently-random-values.enabled = true
integer-overflow-or-underflow.enabled = true
iterators-over-indexing.enabled = true
lazy-delegate.enabled = true
panic-error.enabled = true
reentrancy-1.enabled = true
reentrancy-2.enabled = true
set-code-hash.enabled = true
set-contract-storage.enabled = true
unprotected-mapping-operation.enabled = true
unprotected-self-destruct.enabled = true
unrestricted-transfer-from.enabled = true
unsafe-expect.enabled = true
unsafe-unwrap.enabled = true
unused-return-enum.enabled = true
zero-or-test-address.enabled = true

[vscode]
assert-violation.enabled = true
avoid-core-mem-forget.enabled = true
avoid-format-string.enabled = true
delegate-call.enabled = true
divide-before-multiply.enabled = true
dos-unbounded-operation.enabled = true
dos-unexpected-revert-with-vector.enabled = true
ink-version.enabled = true
insufficiently-random-values.enabled = true
integer-overflow-or-underflow.enabled = true
iterators-over-indexing.enabled = true
lazy-delegate.enabled = true
panic-error.enabled = true
reentrancy-1.enabled = true
reentrancy-2.enabled = true
set-code-hash.enabled = true
set-contract-storage.enabled = true
unprotected-mapping-operation.enabled = true
unprotected-self-destruct.enabled = true
unrestricted-transfer-from.enabled = true
unsafe-expect.enabled = true
unsafe-unwrap.enabled = true
unused-return-enum.enabled = true
zero-or-test-address.enabled = true


[critical]
assert-violation.enabled = false
avoid-core-mem-forget.enabled = false
avoid-format-string.enabled = false
delegate-call.enabled = true
divide-before-multiply.enabled = false
dos-unbounded-operation.enabled = false
dos-unexpected-revert-with-vector.enabled = false
ink-version.enabled = false
insufficiently-random-values.enabled = true
integer-overflow-or-underflow.enabled = true
iterators-over-indexing.enabled = false
lazy-delegate.enabled = true
panic-error.enabled = false
reentrancy-1.enabled = true
reentrancy-2.enabled = true
set-code-hash.enabled = false
set-contract-storage.enabled = true
unprotected-mapping-operation.enabled = true
unprotected-self-destruct.enabled = true
unrestricted-transfer-from.enabled = true
unsafe-expect.enabled = false
unsafe-unwrap.enabled = false
unused-return-enum.enabled = false
zero-or-test-address.enabled = true

[medium]
assert-violation.enabled = false
avoid-core-mem-forget.enabled = false
avoid-format-string.enabled = false
delegate-call.enabled = false
divide-before-multiply.enabled = true
dos-unbounded-operation.enabled = true
dos-unexpected-revert-with-vector.enabled = true
ink-version.enabled = false
insufficiently-random-values.enabled = false
integer-overflow-or-underflow.enabled = false
iterators-over-indexing.enabled = false
lazy-delegate.enabled = false
panic-error.enabled = false
reentrancy-1.enabled = false
reentrancy-2.enabled = false
set-code-hash.enabled = false
set-contract-storage.enabled = false
unprotected-mapping-operation.enabled = false
unprotected-self-destruct.enabled = false
unrestricted-transfer-from.enabled = false
unsafe-expect.enabled = true
unsafe-unwrap.enabled = true
unused-return-enum.enabled = false
zero-or-test-address.enabled = true

[minor]
assert-violation.enabled = false
avoid-core-mem-forget.enabled = false
avoid-format-string.enabled = false
delegate-call.enabled = false
divide-before-multiply.enabled = false
dos-unbounded-operation.enabled = false
dos-unexpected-revert-with-vector.enabled = false
ink-version.enabled = false
insufficiently-random-values.enabled = false
integer-overflow-or-underflow.enabled = false
iterators-over-indexing.enabled = false
lazy-delegate.enabled = false
panic-error.enabled = false
reentrancy-1.enabled = false
reentrancy-2.enabled = false
set-code-hash.enabled = false
set-contract-storage.enabled = false
unprotected-mapping-operation.enabled = false
unprotected-self-destruct.enabled = false
unrestricted-transfer-from.enabled = false
unsafe-expect.enabled = false
unsafe-unwrap.enabled = false
unused-return-enum.enabled = true
zero-or-test-address.enabled = false

[enhancement]
assert-violation.enabled = true
avoid-core-mem-forget.enabled = true
avoid-format-string.enabled = true
delegate-call.enabled = false
divide-before-multiply.enabled = false
dos-unbounded-operation.enabled = false
dos-unexpected-revert-with-vector.enabled = false
ink-version.enabled = true
insufficiently-random-values.enabled = false
integer-overflow-or-underflow.enabled = false
iterators-over-indexing.enabled = true
lazy-delegate.enabled = false
panic-error.enabled = true
reentrancy-1.enabled = false
reentrancy-2.enabled = false
set-code-hash.enabled = false
set-contract-storage.enabled = false
unprotected-mapping-operation.enabled = false
unprotected-self-destruct.enabled = false
unrestricted-transfer-from.enabled = false
unsafe-expect.enabled = false
unsafe-unwrap.enabled = false
unused-return-enum.enabled = true
zero-or-test-address.enabled = false

[custom]
assert-violation.enabled = false
avoid-core-mem-forget.enabled = false
avoid-format-string.enabled = false
delegate-call.enabled = false
divide-before-multiply.enabled = false
dos-unbounded-operation.enabled = false
dos-unexpected-revert-with-vector.enabled = false
ink-version.enabled = false
insufficiently-random-values.enabled = false
integer-overflow-or-underflow.enabled = false
iterators-over-indexing.enabled = false
lazy-delegate.enabled = false
panic-error.enabled = false
reentrancy-1.enabled = false
reentrancy-2.enabled = false
set-code-hash.enabled = false
set-contract-storage.enabled = false
unprotected-mapping-operation.enabled = false
unprotected-self-destruct.enabled = false
unrestricted-transfer-from.enabled = false
unsafe-expect.enabled = false
unsafe-unwrap.enabled = false
unused-return-enum.enabled = false
zero-or-test-address.enabled = false