[auditor]
assert-violation.enabled = true
avoid-core-mem-forget.enabled = false
avoid-format-string.enabled = false
delegate-call.enabled = true
divide-before-multiply.enabled = true
dos-unbounded-operation.enabled = true
dos-unexpected-revert-with-vector.enabled = true
ink-version.enabled = true
insufficiently-random-values.enabled = true
integer-overflow-or-underflow.enabled = true
iterators-over-indexing.enabled = true
lazy-delegate.enabled = true
panic-error.enabled = false
reentrancy-1.enabled = true
reentrancy-2.enabled = true
set-code-hash.enabled = true
set-contract-storage.enabled = true
unprotected-mapping-operation.enabled = true
unprotected-self-destruct.enabled = true
unrestricted-transfer-from.enabled = true
unsafe-expect.enabled = true
unsafe-unwrap.enabled = true
unused-return-enum.enabled = false
zero-or-test-address.enabled = true

[dev]
assert-violation.enabled = true
avoid-core-mem-forget.enabled = true
avoid-format-string.enabled = true
delegate-call.enabled = true
divide-before-multiply.enabled = true
dos-unbounded-operation.enabled = true
dos-unexpected-revert-with-vector.enabled = true
ink-version.enabled = true
insufficiently-random-values.enabled = true
integer-overflow-or-underflow.enabled = true
iterators-over-indexing.enabled = true
lazy-delegate.enabled = true
panic-error.enabled = true
reentrancy-1.enabled = true
reentrancy-2.enabled = true
set-code-hash.enabled = true
set-contract-storage.enabled = true
unprotected-mapping-operation.enabled = true
unprotected-self-destruct.enabled = true
unrestricted-transfer-from.enabled = true
unsafe-expect.enabled = true
unsafe-unwrap.enabled = true
unused-return-enum.enabled = true
zero-or-test-address.enabled = true