[workspace]
exclude = [".cargo", ".vscode", "target"]
members = ["*"]
resolver = "2"

[workspace.dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "51a1cf0" }
common = { path = "../../../common" }
dylint_internal = "=3.1.2"
dylint_linting = "=3.1.2"
