
[package]
edition = "2021"
name = "overflow-check-vulnerable-1"
version = "0.1.0"

[dependencies]
soroban-sdk = { version = "=21.4.0" }

[dev-dependencies]
soroban-sdk = { version = "=21.4.0", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]

[profile.release]
codegen-units = 1
debug = 0
debug-assertions = false
lto = true
opt-level = "z"
overflow-checks = false
panic = "abort"
strip = "symbols"

[profile.release-with-logs]
debug-assertions = true
inherits = "release"
