[package]
edition = "2021"
name = "common-detectors"
version = "0.1.0"

[dependencies]
analysis = { path = "../analysis" }
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "84bb31a36d0df59768829821b068d80da455a7b4", package = "clippy_utils" }
dylint_internal = "5.0.0"
dylint_linting = { git = "https://github.com/trailofbits/dylint.git", rev = "d367947a11f17048e1c73ced41851e906e3648fa" }
if_chain = "=1.0.2"

[package.metadata.rust-analyzer]
rustc_private = true
