name: Release

on:
  push:
    branches:
      - main

env:
  PYTHONUNBUFFERED: 1

jobs:
  filter-paths:
    name: Filter modified paths by PR
    runs-on: ubuntu-latest
    outputs:
      scout-audit: ${{ steps.filter.outputs.scout_audit }}
      dylint-linting: ${{ steps.filter.outputs.dylint_linting }}
      clippy-utils: ${{ steps.filter.outputs.clippy_utils }}
      clippy-config: ${{ steps.filter.outputs.clippy_config }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter Paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            scout_audit:
              - 'apps/cargo-scout-audit/**'
            dylint_linting:
              - 'scout-audit-dylint-linting/**'
            clippy_utils:
              - 'scout-audit-clippy-utils/**'
            clippy_config:
              - 'scout-audit-clippy-config/**'
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          list-files: none
          initial-fetch-depth: 0

  release:
    name: Release
    needs: filter-paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests toml

      - name: Login to crates.io
        run: echo ${{ secrets.CRATES_TOKEN }} | cargo login

      - name: Publish Scout Audit
        if: ${{ needs.filter-paths.outputs.scout-audit == 'true' }}
        run: python scripts/publish-to-crates-io.py --crate-path apps/cargo-scout-audit

      - name: Publish Dylint Linting
        if: ${{ needs.filter-paths.outputs.dylint-linting == 'true' }}
        run: python scripts/publish-to-crates-io.py --crate-path scout-audit-dylint-linting

      - name: Publish Clippy Utils
        if: ${{ needs.filter-paths.outputs.clippy-utils == 'true' }}
        run: python scripts/publish-to-crates-io.py --crate-path scout-audit-clippy-linting

      - name: Publish Clippy Config
        if: ${{ needs.filter-paths.outputs.clippy-config == 'true' }}
        run: python scripts/publish-to-crates-io.py --crate-path scout-audit-clippy-config
