name: Release extension

on:
  pull_request:
    paths:
      - "apps/scout-extension"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VS Code Marketplace
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/scout-extension
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
